apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  namespace: mateapp
spec:
  selector:
    matchLabels:
      app: mateapp
  template:
    metadata:
      labels:
        app: mateapp
    spec:
      containers:
      - name: busybox
        image: ikulyk404/busyboxplus:curl
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 30"]
      restartPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
        